MODEL:
  NAME: "ReIDTrainer" 
  BACKBONE: "ViT-B/16"
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0
  I2T_LOSS_WEIGHT: 1.0
  PRETRAIN_CHOICE: 'imagenet'
  NECK: 'bnneck'
  IF_LABELSMOOTH: 'on'

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

DATASETS:
  NAMES: 'MPDD'
  ROOT_DIR: './data'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 1
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00055
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    # MAX_EPOCHS: 40
    MAX_EPOCHS: 4
    CHECKPOINT_PERIOD: 40
    LOG_PERIOD: 250
    WARMUP_EPOCHS: 5

  STAGE2:
    IMS_PER_BATCH: 32
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000008
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY: 0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 10
    EVAL_PERIOD: 10
    STEPS: [30, 50]

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  EVALUATOR: 'ReIDEvaluator'
  EVAL_PERIOD: 10
  MAX_RANK: 50
  REMOVE_IDENTICAL: False